# Generated by Django 5.0.6 on 2026-04-30 09:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('colleges', '0002_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (9–15 digits, optional leading +).', regex='^\\+?1?\\d{9,15}$')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer Not to Say')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='users/photos/%Y/%m/')),
                ('current_education_level', models.CharField(blank=True, choices=[('class_10', 'Class 10'), ('class_12', 'Class 12'), ('diploma', 'Diploma'), ('graduate', 'Graduate'), ('post_graduate', 'Post Graduate'), ('other', 'Other')], max_length=20)),
                ('twelfth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('twelfth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tenth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tenth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('jee_main_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('jee_advanced_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('neet_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('neet_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('cat_percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mat_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('clat_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('gate_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gmat_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('xat_percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('preferred_degree_level', models.CharField(blank=True, max_length=20)),
                ('preferred_field', models.CharField(blank=True, help_text='e.g. Engineering, Medical', max_length=100)),
                ('budget_min', models.PositiveIntegerField(blank=True, help_text='Annual fee budget in INR', null=True)),
                ('budget_max', models.PositiveIntegerField(blank=True, help_text='Annual fee budget in INR', null=True)),
                ('open_to_hostel', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='colleges.city')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('preferred_states', models.ManyToManyField(blank=True, related_name='preferred_by_users', to='colleges.state')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='colleges.state')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('password_reset', 'Password Reset'), ('phone_verify', 'Phone Verification'), ('email_change', 'Email Change')], max_length=20)),
                ('identifier', models.CharField(help_text='Email address or phone number', max_length=255)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_verifications',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, help_text='Anonymous session identifier', max_length=64)),
                ('activity_type', models.CharField(choices=[('page_view', 'Page View'), ('college_view', 'College View'), ('course_view', 'Course View'), ('search', 'Search'), ('filter_apply', 'Filter Apply'), ('brochure_download', 'Brochure Download'), ('apply_click', 'Apply Click'), ('enquiry_form', 'Enquiry Form'), ('comparison_add', 'Comparison Add'), ('shortlist_add', 'Shortlist Add'), ('shortlist_remove', 'Shortlist Remove')], db_index=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Search query, filter params, scroll depth, etc.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_activities', to='colleges.college')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_activities', to='courses.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activities',
            },
        ),
        migrations.CreateModel(
            name='UserCollegeComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text='Optional label given by user', max_length=100)),
                ('colleges', models.ManyToManyField(related_name='in_comparisons', to='colleges.college')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_college_comparisons',
            },
        ),
        migrations.CreateModel(
            name='UserSavedCollege',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='colleges.college')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_colleges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_saved_colleges',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_email_verified'], name='users_is_acti_9c2147_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['identifier', 'otp_type', 'purpose'], name='otp_verific_identif_d2d06a_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['expires_at'], name='otp_verific_expires_e91cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'activity_type', 'created_at'], name='user_activi_user_id_de49e5_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['college', 'activity_type'], name='user_activi_college_8f8be7_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['session_key', 'created_at'], name='user_activi_session_09f772_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['created_at'], name='user_activi_created_9fa3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='usersavedcollege',
            index=models.Index(fields=['user', 'created_at'], name='user_saved__user_id_e023db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersavedcollege',
            unique_together={('user', 'college')},
        ),
    ]
