# Generated by Django 5.0.6 on 2026-04-30 09:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level', models.CharField(choices=[('ug', 'Undergraduate (UG)'), ('pg', 'Postgraduate (PG)'), ('phd', 'Doctorate (PhD)'), ('diploma', 'Diploma'), ('pg_diploma', 'PG Diploma'), ('certificate', 'Certificate'), ('integrated', 'Integrated (UG + PG)'), ('fellowship', 'Fellowship')], max_length=15, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'degree_levels',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('online', 'Online'), ('distance', 'Distance / Correspondence'), ('hybrid', 'Hybrid (Blended)'), ('weekend', 'Weekend')], db_index=True, default='full_time', max_length=15)),
                ('duration_years', models.PositiveSmallIntegerField()),
                ('total_semesters', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_credits', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('has_lateral_entry', models.BooleanField(default=False, help_text='Lateral entry available (e.g. diploma holders)')),
                ('lateral_entry_year', models.PositiveSmallIntegerField(blank=True, help_text='Which year lateral entry joins', null=True)),
                ('total_fee', models.PositiveIntegerField(blank=True, db_index=True, help_text='Total programme fee in INR', null=True)),
                ('fee_per_year', models.PositiveIntegerField(blank=True, help_text='Approx first-year fee in INR', null=True)),
                ('hostel_fee_per_year', models.PositiveIntegerField(blank=True, null=True)),
                ('min_percentage_required', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum aggregate % (usually in 10+2)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_intake', models.PositiveSmallIntegerField(blank=True, help_text='Total sanctioned seats', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('discontinued', 'Discontinued')], db_index=True, default='draft', max_length=15)),
                ('is_featured', models.BooleanField(default=False)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='colleges.college')),
                ('degree_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.degreelevel')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseEligibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_percentage_10th', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_percentage_12th', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_percentage_graduation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_percentage_ug', models.DecimalField(blank=True, decimal_places=2, help_text='For PG courses', max_digits=5, null=True)),
                ('required_subjects_12th', models.JSONField(blank=True, default=list)),
                ('required_subjects_grad', models.JSONField(blank=True, default=list)),
                ('min_work_experience_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('work_experience_description', models.TextField(blank=True)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('open_to_nri', models.BooleanField(default=False)),
                ('open_to_foreign_nationals', models.BooleanField(default=False)),
                ('domicile_requirement', models.CharField(blank=True, max_length=255)),
                ('additional_criteria', models.TextField(blank=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='courses.course')),
            ],
            options={
                'db_table': 'course_eligibilities',
            },
        ),
        migrations.CreateModel(
            name='DegreeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name: Bachelor of Technology', max_length=100, unique=True)),
                ('short_name', models.CharField(help_text='B.Tech', max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('typical_duration_years', models.PositiveSmallIntegerField(blank=True, help_text='Standard duration (can be overridden per course)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('degree_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degree_types', to='courses.degreelevel')),
            ],
            options={
                'db_table': 'degree_types',
                'ordering': ['display_order', 'short_name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='degree_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.degreetype'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.department'),
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='courses.department')),
            ],
            options={
                'db_table': 'specializations',
                'ordering': ['name'],
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.specialization'),
        ),
        migrations.CreateModel(
            name='CourseEntranceExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('min_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('min_percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_exams', to='courses.course')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_mappings', to='colleges.entranceexam')),
            ],
            options={
                'db_table': 'course_entrance_exams',
                'unique_together': {('course', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='CourseFeeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(blank=True, help_text='e.g. 2024-25', max_length=10)),
                ('year_number', models.PositiveSmallIntegerField(help_text='Programme year: 1, 2, 3, 4')),
                ('semester_number', models.PositiveSmallIntegerField(blank=True, help_text='Odd/even semester within the year', null=True)),
                ('tuition_fee', models.PositiveIntegerField(default=0)),
                ('exam_fee', models.PositiveIntegerField(default=0)),
                ('library_fee', models.PositiveIntegerField(default=0)),
                ('lab_fee', models.PositiveIntegerField(default=0)),
                ('sports_fee', models.PositiveIntegerField(default=0)),
                ('development_fee', models.PositiveIntegerField(default=0)),
                ('admission_fee', models.PositiveIntegerField(default=0)),
                ('miscellaneous_fee', models.PositiveIntegerField(default=0)),
                ('total_fee', models.PositiveIntegerField(default=0, help_text='Sum of all components for this period')),
                ('caution_deposit', models.PositiveIntegerField(default=0)),
                ('is_latest', models.BooleanField(default=True, help_text='Mark False for historical fee data')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure', to='courses.course')),
            ],
            options={
                'db_table': 'course_fee_structures',
                'ordering': ['year_number', 'semester_number'],
                'indexes': [models.Index(fields=['course', 'year_number'], name='course_fee__course__4c2f93_idx'), models.Index(fields=['course', 'is_latest'], name='course_fee__course__682840_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoursePlacementStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('batch', models.CharField(blank=True, max_length=20)),
                ('total_students_eligible', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_students_placed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('placement_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_package_lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('highest_package_lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('top_recruiters_snapshot', models.JSONField(blank=True, default=list)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_stats', to='courses.course')),
            ],
            options={
                'db_table': 'course_placement_stats',
                'ordering': ['-year'],
                'unique_together': {('course', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CourseSeatMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(help_text='e.g. 2024-25', max_length=10)),
                ('category', models.CharField(choices=[('general', 'General / UR'), ('obc', 'OBC'), ('obc_ncl', 'OBC-NCL'), ('sc', 'SC'), ('st', 'ST'), ('ews', 'EWS'), ('pwd', 'PwD'), ('nri', 'NRI'), ('management', 'Management Quota'), ('foreign', 'Foreign National'), ('tfws', 'Tuition Fee Waiver Scheme')], max_length=20)),
                ('total_seats', models.PositiveSmallIntegerField(default=0)),
                ('filled_seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_matrix', to='courses.course')),
            ],
            options={
                'db_table': 'course_seat_matrices',
                'indexes': [models.Index(fields=['course', 'academic_year'], name='course_seat_course__5ae88c_idx')],
                'unique_together': {('course', 'academic_year', 'category')},
            },
        ),
        migrations.CreateModel(
            name='CourseSyllabus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester', models.PositiveSmallIntegerField()),
                ('subject_name', models.CharField(max_length=255)),
                ('subject_code', models.CharField(blank=True, max_length=30)),
                ('credits', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_core', models.BooleanField(default=True)),
                ('is_elective', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='courses.course')),
            ],
            options={
                'db_table': 'course_syllabi',
                'ordering': ['semester', 'subject_name'],
                'indexes': [models.Index(fields=['course', 'semester'], name='course_syll_course__719512_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['college', 'status'], name='courses_college_c37138_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['degree_level', 'degree_type'], name='courses_degree__b3801a_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department', 'specialization'], name='courses_departm_1fa126_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['mode', 'status'], name='courses_mode_3f1033_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['total_fee'], name='courses_total_f_c59df0_idx'),
        ),
    ]
