# Generated by Django 5.0.6 on 2026-04-30 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeLeadSummary',
            fields=[
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lead_summary', serialize=False, to='colleges.college')),
                ('total_leads', models.PositiveIntegerField(default=0)),
                ('leads_this_month', models.PositiveIntegerField(default=0)),
                ('leads_this_week', models.PositiveIntegerField(default=0)),
                ('leads_today', models.PositiveIntegerField(default=0)),
                ('total_brochure_downloads', models.PositiveIntegerField(default=0)),
                ('total_apply_clicks', models.PositiveIntegerField(default=0)),
                ('total_converted', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_lead_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'college_lead_summaries',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('current_education', models.CharField(blank=True, max_length=50)),
                ('exam_score_info', models.CharField(blank=True, help_text='Free text: JEE rank, NEET score, etc.', max_length=255)),
                ('source', models.CharField(choices=[('brochure_download', 'Brochure Download'), ('apply_now', 'Apply Now'), ('enquiry_form', 'Enquiry Form'), ('comparison', 'College Comparison'), ('shortlist', 'Shortlist / Save'), ('direct', 'Direct (Admin-created)')], db_index=True, max_length=30)),
                ('source_url', models.URLField(blank=True, help_text='Page URL where action happened')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_term', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('notified', 'College Notified'), ('contacted', 'College Contacted Student'), ('qualified', 'Qualified'), ('interested', 'Student Interested'), ('not_interested', 'Student Not Interested'), ('converted', 'Converted (Enrolled)'), ('lost', 'Lost'), ('duplicate', 'Duplicate'), ('junk', 'Junk / Invalid')], db_index=True, default='new', max_length=20)),
                ('email_sent_to_college', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notification_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('status_change', 'Status Changed'), ('email_sent', 'Email Sent to College'), ('note_added', 'Note Added'), ('call_logged', 'Call Logged'), ('duplicate_merged', 'Marked Duplicate')], max_length=20)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'lead_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Internal notes are not shared with the college')),
            ],
            options={
                'db_table': 'lead_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, max_length=10)),
                ('report_date', models.DateField(db_index=True)),
                ('total_leads', models.PositiveIntegerField(default=0)),
                ('new_leads', models.PositiveIntegerField(default=0)),
                ('contacted_leads', models.PositiveIntegerField(default=0)),
                ('converted_leads', models.PositiveIntegerField(default=0)),
                ('lost_leads', models.PositiveIntegerField(default=0)),
                ('junk_leads', models.PositiveIntegerField(default=0)),
                ('brochure_downloads', models.PositiveIntegerField(default=0)),
                ('apply_clicks', models.PositiveIntegerField(default=0)),
                ('enquiry_form_submits', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=2, help_text='converted_leads / total_leads × 100', max_digits=5, null=True)),
                ('leads_by_source', models.JSONField(blank=True, default=dict)),
                ('leads_by_state', models.JSONField(blank=True, default=dict)),
                ('top_courses', models.JSONField(blank=True, default=list)),
                ('leads_by_utm_source', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lead_reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='BrochureDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('brochure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_events', to='colleges.brochure')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brochure_download_events', to='colleges.college')),
            ],
            options={
                'db_table': 'brochure_downloads',
            },
        ),
    ]
