# Generated by Django 5.0.6 on 2026-04-30 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0002_initial'),
        ('courses', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brochuredownload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brochure_downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='brochure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='colleges.brochure'),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='colleges.city'),
        ),
        migrations.AddField(
            model_name='lead',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='lead',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='courses.course'),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='colleges.state'),
        ),
        migrations.AddField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null only for legacy / pre-auth leads', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brochuredownload',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brochure_downloads', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadnote',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadreport',
            name='college',
            field=models.ForeignKey(blank=True, help_text='NULL = platform-wide aggregate', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_reports', to='colleges.college'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['college', 'status', 'created_at'], name='leads_college_389402_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email', 'college'], name='leads_email_7f886b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source', 'created_at'], name='leads_source_508ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['utm_source', 'utm_campaign'], name='leads_utm_sou_332ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at', 'status'], name='leads_created_836b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['college', 'created_at'], name='leads_college_a945f4_idx'),
        ),
        migrations.AddIndex(
            model_name='brochuredownload',
            index=models.Index(fields=['college', 'downloaded_at'], name='brochure_do_college_cf5e64_idx'),
        ),
        migrations.AddIndex(
            model_name='brochuredownload',
            index=models.Index(fields=['brochure', 'downloaded_at'], name='brochure_do_brochur_4307be_idx'),
        ),
        migrations.AddIndex(
            model_name='brochuredownload',
            index=models.Index(fields=['user', 'downloaded_at'], name='brochure_do_user_id_9b90d4_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead', 'created_at'], name='lead_activi_lead_id_0fa01f_idx'),
        ),
        migrations.AddIndex(
            model_name='leadreport',
            index=models.Index(fields=['report_type', 'report_date'], name='lead_report_report__5ba203_idx'),
        ),
        migrations.AddIndex(
            model_name='leadreport',
            index=models.Index(fields=['college', 'report_date'], name='lead_report_college_c86413_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leadreport',
            unique_together={('report_type', 'report_date', 'college')},
        ),
    ]
