# Generated by Django 5.0.6 on 2026-04-30 09:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0002_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewHelpfulness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_helpful', models.BooleanField(help_text='True = helpful, False = not helpful')),
            ],
            options={
                'db_table': 'review_helpfulness',
            },
        ),
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='reviews/media/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'review_media',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ReviewModerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged'), ('restored', 'Restored'), ('edited', 'Edited by Admin')], max_length=20)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'review_moderation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reply_text', models.TextField()),
                ('is_college_reply', models.BooleanField(default=False, help_text='True = college official reply')),
                ('is_admin_reply', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'review_replies',
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('fake', 'Fake Review'), ('spam', 'Spam'), ('abusive', 'Abusive Language'), ('irrelevant', 'Irrelevant Content'), ('conflict', 'Conflict of Interest'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'review_reports',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('placement_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('faculty_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('infrastructure_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('campus_life_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('value_for_money_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('hostel_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sports_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('library_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('industry_exposure_rating', models.PositiveSmallIntegerField(blank=True, help_text='Industry visits, internships, guest lectures', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=255)),
                ('pros', models.TextField(help_text='What the reviewer liked')),
                ('cons', models.TextField(blank=True, help_text='What could be better')),
                ('advice', models.TextField(blank=True, help_text='Advice to future students / aspirants')),
                ('batch_year', models.PositiveSmallIntegerField(blank=True, help_text='Year of joining', null=True)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, help_text='Year of passing out', null=True)),
                ('is_current_student', models.BooleanField(default=False)),
                ('program_studied', models.CharField(blank=True, max_length=255)),
                ('is_verified_student', models.BooleanField(default=False, help_text="Admin has verified the student's enrolment")),
                ('is_anonymous', models.BooleanField(default=False, help_text='Display name hidden from public')),
                ('verification_doc', models.FileField(blank=True, help_text='Student ID / marksheet uploaded by reviewer', null=True, upload_to='reviews/verification/%Y/%m/')),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('not_helpful_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Moderation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Re-review')], db_index=True, default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='colleges.college')),
                ('course', models.ForeignKey(blank=True, help_text='Course the reviewer studied', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='courses.course')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
