# Generated by Django 5.0.6 on 2026-04-30 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brochure',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brochures', to='courses.course'),
        ),
        migrations.AddField(
            model_name='categorycutoff',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='courses.course'),
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='colleges.city'),
        ),
        migrations.AddField(
            model_name='college',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colleges', to='colleges.area'),
        ),
        migrations.AddField(
            model_name='college',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colleges', to='colleges.city'),
        ),
        migrations.AddField(
            model_name='categorycutoff',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brochures', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='approval',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='admissionprocess',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_steps', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='accreditation',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreditations', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='collegeentranceexam',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_exams', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='collegefacilitymapping',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college'),
        ),
        migrations.AddField(
            model_name='collegemedia',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='college',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colleges', to='colleges.country'),
        ),
        migrations.AddField(
            model_name='collegeentranceexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepting_colleges', to='colleges.entranceexam'),
        ),
        migrations.AddField(
            model_name='categorycutoff',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutoffs', to='colleges.entranceexam'),
        ),
        migrations.AddField(
            model_name='collegefacilitymapping',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.facility'),
        ),
        migrations.AddField(
            model_name='college',
            name='facilities',
            field=models.ManyToManyField(blank=True, through='colleges.CollegeFacilityMapping', to='colleges.facility'),
        ),
        migrations.AddField(
            model_name='hosteldetail',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_details', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='importantdate',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_dates', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='importantdate',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.entranceexam'),
        ),
        migrations.AddField(
            model_name='nirfranking',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nirf_rankings', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='otherranking',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_rankings', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='placementstatistics',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_stats', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='scholarshipscheme',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='colleges.country'),
        ),
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colleges', to='colleges.state'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='colleges.state'),
        ),
        migrations.AddField(
            model_name='toprecruiter',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_recruiters', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='university',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities', to='colleges.city'),
        ),
        migrations.AddField(
            model_name='university',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities', to='colleges.state'),
        ),
        migrations.AddField(
            model_name='college',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated_colleges', to='colleges.university'),
        ),
        migrations.AddIndex(
            model_name='brochure',
            index=models.Index(fields=['college', 'is_active'], name='brochures_college_a46e46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='admissionprocess',
            unique_together={('college', 'step_number')},
        ),
        migrations.AddIndex(
            model_name='accreditation',
            index=models.Index(fields=['college', 'body', 'is_active'], name='accreditati_college_16b886_idx'),
        ),
        migrations.AddIndex(
            model_name='collegemedia',
            index=models.Index(fields=['college', 'media_type', 'is_active'], name='college_med_college_30233a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collegeentranceexam',
            unique_together={('college', 'exam')},
        ),
        migrations.AddIndex(
            model_name='categorycutoff',
            index=models.Index(fields=['college', 'year', 'category'], name='category_cu_college_86581d_idx'),
        ),
        migrations.AddIndex(
            model_name='categorycutoff',
            index=models.Index(fields=['exam', 'year'], name='category_cu_exam_id_daae3e_idx'),
        ),
        migrations.AddIndex(
            model_name='categorycutoff',
            index=models.Index(fields=['course', 'year', 'category'], name='category_cu_course__9513ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collegefacilitymapping',
            unique_together={('college', 'facility')},
        ),
        migrations.AddIndex(
            model_name='importantdate',
            index=models.Index(fields=['college', 'year'], name='important_d_college_a04cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='nirfranking',
            index=models.Index(fields=['year', 'category', 'rank'], name='nirf_rankin_year_8a1afc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nirfranking',
            unique_together={('college', 'year', 'category')},
        ),
        migrations.AddIndex(
            model_name='otherranking',
            index=models.Index(fields=['college', 'year'], name='other_ranki_college_b4c9d0_idx'),
        ),
        migrations.AddIndex(
            model_name='placementstatistics',
            index=models.Index(fields=['college', 'year'], name='placement_s_college_d13031_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='placementstatistics',
            unique_together={('college', 'year', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('country', 'name')},
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state', 'is_active'], name='cities_state_i_3b7453_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'name')},
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['status', 'is_featured'], name='colleges_status_fbaf10_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['state', 'city', 'status'], name='colleges_state_i_ca85b7_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['college_type', 'ownership_type', 'status'], name='colleges_college_2885e3_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['naac_grade'], name='colleges_naac_gr_cad172_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['min_fee_per_year', 'max_fee_per_year'], name='colleges_min_fee_093536_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['avg_rating', 'total_reviews'], name='colleges_avg_rat_daffeb_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['nirf_ranking'], name='colleges_nirf_ra_248579_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['is_aicte_approved', 'is_ugc_recognized'], name='colleges_is_aict_0177b1_idx'),
        ),
    ]
