# Generated by Django 5.0.6 on 2026-05-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='External cover image URL (used when cover_image file is not uploaded)'),
        ),
        migrations.AddField(
            model_name='college',
            name='logo_color',
            field=models.CharField(blank=True, help_text='Hex color for logo background e.g. #003366', max_length=20),
        ),
        migrations.AddField(
            model_name='college',
            name='logo_initials',
            field=models.CharField(blank=True, help_text='Short initials shown when logo is absent e.g. IITB', max_length=10),
        ),
        migrations.AddField(
            model_name='hosteldetail',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text='["Wi-Fi", "Gym", "Mess", "Laundry", "Common Room", ...]'),
        ),
        migrations.AlterField(
            model_name='college',
            name='notable_alumni',
            field=models.JSONField(blank=True, default=list, help_text='[{name, achievement, year}]'),
        ),
    ]
